name: Local CI/CD (self-hosted)

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build JAR
        run: mvn -B clean package -DskipTests

      - name: Build Docker image
        run: docker build -t system-auto-build-springboot-app:latest .

      - name: Stop and remove existing container (if any)
        run: |
          $container = docker ps -aq -f "name=springboot-app"
          if ($container) {
              docker stop $container
              docker rm $container
          }

      - name: Wait for MySQL container
        run: |
          Write-Host "Waiting for MySQL to be ready..."
          do {
              Start-Sleep -Seconds 3
              $status = docker exec mysql-db mysqladmin ping -uroot -pAshish@2100 --silent
          } while ($status -ne "mysqld is alive")
          Write-Host "MySQL is ready."

      - name: Run new Spring Boot container
        run: |
          docker run -d --name springboot-app -p 9090:8081 `
            -e SPRING_PROFILES_ACTIVE=docker `
            system-auto-build-springboot-app:latest

      - name: Confirm container is running
        run: docker ps | Select-String "springboot-app"
