name: Local CI/CD (self-hosted)

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted   # runs on your machine (the registered runner)

    steps:
      # Step 1: Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Step 3: Build Spring Boot JAR
      - name: Build JAR
        run: mvn clean package -DskipTests

      # Step 4: Deploy using Docker Compose
      - name: Deploy with Docker Compose
        run: |
          # Stop and remove old containers
          docker-compose down
          
          # Build images and start containers in detached mode
          docker-compose up -d --build

      # Step 5: Show running containers
      - name: List running containers
        run: docker ps
