name: Local CI/CD (self-hosted)

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      # Step 3: Build JAR using Maven
      - name: Build JAR
        shell: powershell
        run: mvn -B clean package -DskipTests

      # Step 4: Build Docker image
      - name: Build Docker image
        shell: powershell
        run: docker build -t system-auto-build-springboot-app:latest .

      # Step 5: Stop and remove existing Spring Boot container
      - name: Stop and remove existing container (if any)
        shell: powershell
        run: |
          $container = docker ps -aq -f "name=springboot-app"
          if ($container) {
              Write-Host "Stopping existing Spring Boot container..."
              docker stop $container
              docker rm $container
          } else {
              Write-Host "No existing Spring Boot container found."
          }

      # Step 6: Wait for MySQL container to be ready
      - name: Wait for MySQL container
        shell: powershell
        run: |
          Write-Host "Waiting for MySQL to be ready..."
          do {
              Start-Sleep -Seconds 3
              $status = docker exec mysql-db mysqladmin ping -uroot -pAshish@2100 --silent
          } while ($status -ne "mysqld is alive")
          Write-Host "MySQL is ready."

      # Step 7: Run new Spring Boot container
      - name: Run new Spring Boot container
        shell: powershell
        run: |
          docker run -d --name springboot-app -p 9090:8081 `
            -e SPRING_PROFILES_ACTIVE=docker `
            system-auto-build-springboot-app:latest

      # Step 8: Confirm container is running
      - name: Confirm container is running
        shell: powershell
        run: docker ps | Select-String "springboot-app"
