name: Local CI/CD (self-hosted)

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted  # your self-hosted Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build JAR
        run: mvn -B clean package -DskipTests

      - name: Build Docker image
        run: docker build -t system-auto-build-springboot-app:latest .

      - name: Stop existing container (if any)
        run: |
          docker stop springboot-app || true
          docker rm springboot-app || true

      - name: Run container
        run: docker run -d --name springboot-app -p 9090:8081 system-auto-build-springboot-app:latest
