name: Local CI/CD (self-hosted)

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Maven   # ✅ Add this here
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.9.9

      - name: Build JAR
        run: mvn -B clean package -DskipTests

      - name: Build Docker image
        run: docker build -t system-auto-build-springboot-app:latest .

      - name: Stop and remove existing container (if any)
        shell: bash
        run: |
          docker stop springboot-app || true
          docker rm springboot-app || true

      - name: Wait for MySQL container
        shell: bash
        run: |
          echo "Waiting for MySQL to be ready..."
          until docker exec mysql-db mysqladmin ping -uroot -pAshish@2100 --silent; do
            sleep 3
          done
          echo "MySQL is ready."

      - name: Run new Spring Boot container
        shell: bash
        run: |
          docker run -d --name springboot-app -p 9090:8081 \
            -e SPRING_PROFILES_ACTIVE=docker \
            system-auto-build-springboot-app:latest

      - name: Confirm container is running
        run: docker ps | grep springboot-app
